version: '3.3'

services:
  couchdb:
      container_name: couchdb-image
      image: 'couchdb:2.2'
      networks:
        - medic-net
      ports:
        - "5984:5984"
        - "4370:4369"
        - "9101:9100"
      env_file:
        - ./.couch
      volumes:
        - couchdb-data:/opt/couchdb/data
        - ./local.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb-data:

networks:
  medic-net:
    labels:
      com.medic-net.description: "docker containers compose internal network"
