version: '3.3'

services:
  webapp:
    build: .
    container_name: medic
    ports:
      - "5988:5988"
    networks:
      - medic-net
    volumes:
      - .:/srv/
      - ./api/logs/:/srv/api/logs/
      - ./sentinel/logs:/srv/sentinel/logs/
    depends_on:
      - couchdb
    env_file:
      - ./.env
      - ./.couch

  couchdb:
      container_name: couchdb
      image: 'couchdb:2.2'
      networks:
        - medic-net
      ports:
        - "5984:5984"
        - "4370:4369"
        - "9101:9100"
      env_file:
        - ./.couch
      volumes:
        - couchdb-data:/opt/couchdb/data
        - ./local.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb-data:

networks:
  medic-net:
    labels:
      com.medic-net.description: "docker containers compose internal network"
