version: '3.3'

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "7007:80"
    environment:
      - NGINX_PORT=80
    networks:
      - medic-net
    depends_on:
      - couchdb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/medic.lg-apps.com:/etc/nginx/sites-enabled/default.lg-apps.com

  webapp:
    build: .
    container_name: medic
    hostname: medic
    ports:
      - "5988:5988"
    networks:
      - medic-net
    volumes:
      - .:/srv/
      - ./api/logs/:/srv/api/logs/
      - ./sentinel/logs:/srv/sentinel/logs/
    depends_on:
      - couchdb
    env_file:
      - ./.env
      - ./.couch

  couchdb:
      container_name: couchdb
      image: 'couchdb:2.2'
      networks:
        - medic-net
      ports:
        - "5984:5984"
        - "4370:4369"
        - "9101:9100"
      env_file:
        - ./.couch
      volumes:
        - couchdb-data:/opt/couchdb/data
        - ./local.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb-data:

networks:
  medic-net:
    labels:
      com.medic-net.description: "docker containers compose internal network"
